POST http://localhost:3333/api/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNCwiZW1haWwiOiJ0ZXN0ZTIwQGdtYWlsLmNvbSIsIm5hbWUiOiJUZXN0ZTIwIn0sImlhdCI6MTc1NTM2MTg4NCwiZXhwIjoxNzU1MzY1NDg0fQ.eeGVtPeS6Y7593wTi2e4OFkBmuej8p7KA1pG5OeWks8

{
    "name": "item17",
    "location_id": 12,
    "description": "nada"
}

###
GET http://localhost:3333/api/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNCwiZW1haWwiOiJ0ZXN0ZTIwQGdtYWlsLmNvbSIsIm5hbWUiOiJUZXN0ZTIwIn0sImlhdCI6MTc1NTM2MTg4NCwiZXhwIjoxNzU1MzY1NDg0fQ.eeGVtPeS6Y7593wTi2e4OFkBmuej8p7KA1pG5OeWks8

###
PUT http://localhost:3333/api/items/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNCwiZW1haWwiOiJ0ZXN0ZTIwQGdtYWlsLmNvbSIsIm5hbWUiOiJUZXN0ZTIwIn0sImlhdCI6MTc1NTM2MTg4NCwiZXhwIjoxNzU1MzY1NDg0fQ.eeGVtPeS6Y7593wTi2e4OFkBmuej8p7KA1pG5OeWks8

{
    "name": "sofa1"
    //"location_id": 12
}

###
DELETE http://localhost:3333/api/items/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyNCwiZW1haWwiOiJ0ZXN0ZTIwQGdtYWlsLmNvbSIsIm5hbWUiOiJUZXN0ZTIwIn0sImlhdCI6MTc1NTM2MTg4NCwiZXhwIjoxNzU1MzY1NDg0fQ.eeGVtPeS6Y7593wTi2e4OFkBmuej8p7KA1pG5OeWks8
