POST http://localhost:3333/api/locations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyOSwiZW1haWwiOiJ0ZXN0ZTIxQGdtYWlsLmNvbSIsIm5hbWUiOiJUZXN0ZTIifSwiaWF0IjoxNzU1NTM4MTE4LCJleHAiOjE3NTU1NDE3MTh9.NTlq6I9YZIWIDb1t9Itv4kzqU5ZoQMDf3SmTjzcGTtI

{
    "name": "Gaveta Banheiro 5"
}

###
GET http://localhost:3333/api/locations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyOSwiZW1haWwiOiJ0ZXN0ZTIxQGdtYWlsLmNvbSIsIm5hbWUiOiJUZXN0ZTIifSwiaWF0IjoxNzU1NTQyNTQ3LCJleHAiOjE3NTU1NDYxNDd9.Do-ZOLqSABshe-uRmdUKSQ8_QW7x71VFiNLClkiRTvQ

###
PUT http://localhost:3333/api/locations/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyOSwiZW1haWwiOiJ0ZXN0ZTIxQGdtYWlsLmNvbSIsIm5hbWUiOiJUZXN0ZTIifSwiaWF0IjoxNzU1NTQyNTQ3LCJleHAiOjE3NTU1NDYxNDd9.Do-ZOLqSABshe-uRmdUKSQ8_QW7x71VFiNLClkiRTvQ

{
    "name": "Cama"
}

###
DELETE http://localhost:3333/api/locations/15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyOSwiZW1haWwiOiJ0ZXN0ZTIxQGdtYWlsLmNvbSIsIm5hbWUiOiJUZXN0ZTIifSwiaWF0IjoxNzU1NTM4MTE4LCJleHAiOjE3NTU1NDE3MTh9.NTlq6I9YZIWIDb1t9Itv4kzqU5ZoQMDf3SmTjzcGTtI