POST http://localhost:3333/api/locations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxOSwiZW1haWwiOiJwcmlzY0BnbWFpbC5jb20iLCJuYW1lIjoiUHJpcyJ9LCJpYXQiOjE3NTUxOTE1NTgsImV4cCI6MTc1NTE5NTE1OH0.Gp2nUv3CgZI114AfoklrIkcUAVLDxPIrzaMBAv7HCTA

{
    "name": "armário"
}

###
GET http://localhost:3333/api/locations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxOSwiZW1haWwiOiJwcmlzY0BnbWFpbC5jb20iLCJuYW1lIjoiUHJpcyJ9LCJpYXQiOjE3NTUxOTE1NTgsImV4cCI6MTc1NTE5NTE1OH0.Gp2nUv3CgZI114AfoklrIkcUAVLDxPIrzaMBAv7HCTA

###
PUT http://localhost:3333/api/locations/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxOSwiZW1haWwiOiJwcmlzY0BnbWFpbC5jb20iLCJuYW1lIjoiUHJpcyJ9LCJpYXQiOjE3NTUxOTE1NTgsImV4cCI6MTc1NTE5NTE1OH0.Gp2nUv3CgZI114AfoklrIkcUAVLDxPIrzaMBAv7HCTA

{
    "name": "sofa 1"
}

###
DELETE http://localhost:3333/api/locations/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxOSwiZW1haWwiOiJwcmlzY0BnbWFpbC5jb20iLCJuYW1lIjoiUHJpcyJ9LCJpYXQiOjE3NTUxOTE1NTgsImV4cCI6MTc1NTE5NTE1OH0.Gp2nUv3CgZI114AfoklrIkcUAVLDxPIrzaMBAv7HCTA