POST http://localhost:3333/api/users
Content-Type: application/json

{
    "name": "Jessica",
    "email":"jessica@gmail.com",
    "password": "123456"
}

###
PUT http://localhost:3333/api/users/11
Content-Type: application/json

{
    "name": "NovoNome Jess10",
    "email": "novoemai101@example.com",
    "password": "novaSenha789"
}

###
DELETE http://localhost:3333/api/users/11

###
GET http://localhost:3333/api/users/11

### Buscar usuário por nome
GET http://localhost:3333/api/users/name/NovoNome Jess10


### Buscar usuário por email
GET http://localhost:3333/api/users/email/priscila@gmail.com
